const database = [
  // ==========================================
  // PARTE 1: FC PORTO (12 EQUIPAS)
  // ==========================================
  {
    "id": "por_1978",
    "nomeEquipa": "Porto 1978",
    "jogadores": [
      { "nome": "Fonseca", "posicoes": ["GR"], "ovr": 78 },
      { "nome": "Torres", "posicoes": ["GR"], "ovr": 72 },
      { "nome": "Gabriel", "posicoes": ["DD"], "ovr": 79 },
      { "nome": "Teixeirinha", "posicoes": ["DD", "DE"], "ovr": 74 },
      { "nome": "João Pinto", "posicoes": ["DD"], "ovr": 75 },
      { "nome": "Carlos Simões", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "Alfredo Murça", "posicoes": ["DC", "DE"], "ovr": 78 },
      { "nome": "Freitas", "posicoes": ["DC"], "ovr": 76 },
      { "nome": "Liminha", "posicoes": ["DE"], "ovr": 75 },
      { "nome": "Rodolfo Reis", "posicoes": ["MC"], "ovr": 81 },
      { "nome": "António Oliveira", "posicoes": ["MC"], "ovr": 86 },
      { "nome": "Octávio Machado", "posicoes": ["MC"], "ovr": 80 },
      { "nome": "Frasco", "posicoes": ["MC"], "ovr": 79 },
      { "nome": "Ademir Vieira", "posicoes": ["MC"], "ovr": 77 },
      { "nome": "Celso", "posicoes": ["MC"], "ovr": 73 },
      { "nome": "Seninho", "posicoes": ["EXD", "EXE"], "ovr": 82 },
      { "nome": "Duda", "posicoes": ["EXE", "EXD"], "ovr": 80 },
      { "nome": "Taí", "posicoes": ["EXD"], "ovr": 74 },
      { "nome": "Vital", "posicoes": ["PL"], "ovr": 75 },
      { "nome": "Fernando Gomes", "posicoes": ["PL"], "ovr": 88 },
      { "nome": "Mário Gonzalez", "posicoes": ["PL"], "ovr": 76 },
      { "nome": "Nazaré", "posicoes": ["PL"], "ovr": 72 },
      { "nome": "Mirobaldo", "posicoes": ["PL"], "ovr": 74 }
    ]
  },
  {
    "id": "por_1987",
    "nomeEquipa": "Porto 1987",
    "jogadores": [
      { "nome": "Józef Młynarczyk", "posicoes": ["GR"], "ovr": 84 },
      { "nome": "Zé Beto", "posicoes": ["GR"], "ovr": 77 },
      { "nome": "João Pinto", "posicoes": ["DD"], "ovr": 85 },
      { "nome": "Bandeirinha", "posicoes": ["DD", "MC"], "ovr": 76 },
      { "nome": "Celso Vieira", "posicoes": ["DC"], "ovr": 82 },
      { "nome": "Eduardo Luís", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "Lima Pereira", "posicoes": ["DC"], "ovr": 79 },
      { "nome": "Festas", "posicoes": ["DC"], "ovr": 71 },
      { "nome": "Augusto Inácio", "posicoes": ["DE"], "ovr": 81 },
      { "nome": "Laureta", "posicoes": ["DE"], "ovr": 73 },
      { "nome": "António André", "posicoes": ["MC"], "ovr": 83 },
      { "nome": "Quim", "posicoes": ["MC"], "ovr": 81 },
      { "nome": "António Sousa", "posicoes": ["MC"], "ovr": 82 },
      { "nome": "Frasco", "posicoes": ["MC"], "ovr": 78 },
      { "nome": "Elói", "posicoes": ["MC"], "ovr": 75 },
      { "nome": "Vermelhinho", "posicoes": ["EXE"], "ovr": 77 },
      { "nome": "Paulo Futre", "posicoes": ["EXE", "EXD"], "ovr": 91 },
      { "nome": "Rabah Madjer", "posicoes": ["EXD", "PL"], "ovr": 90 },
      { "nome": "Jaime Magalhães", "posicoes": ["EXD"], "ovr": 81 },
      { "nome": "Fernando Gomes", "posicoes": ["PL"], "ovr": 87 },
      { "nome": "Juary", "posicoes": ["PL"], "ovr": 81 },
      { "nome": "Casagrande", "posicoes": ["PL"], "ovr": 78 },
      { "nome": "Walter Casagrande", "posicoes": ["PL"], "ovr": 76 }
    ]
  },
  {
    "id": "por_1995",
    "nomeEquipa": "Porto 1995",
    "jogadores": [
      { "nome": "Vítor Baía", "posicoes": ["GR"], "ovr": 87 },
      { "nome": "Lars Eriksson", "posicoes": ["GR"], "ovr": 74 },
      { "nome": "Carlos Secretário", "posicoes": ["DD"], "ovr": 80 },
      { "nome": "João Pinto", "posicoes": ["DD"], "ovr": 76 },
      { "nome": "Aloísio", "posicoes": ["DC"], "ovr": 83 },
      { "nome": "Jorge Costa", "posicoes": ["DC"], "ovr": 82 },
      { "nome": "Zé Carlos", "posicoes": ["DC"], "ovr": 77 },
      { "nome": "Rui Jorge", "posicoes": ["DE"], "ovr": 78 },
      { "nome": "Paulinho Santos", "posicoes": ["DE", "MC"], "ovr": 80 },
      { "nome": "Emerson", "posicoes": ["MC"], "ovr": 81 },
      { "nome": "Rui Barros", "posicoes": ["MC"], "ovr": 82 },
      { "nome": "Latapy", "posicoes": ["MC"], "ovr": 80 },
      { "nome": "Kulkov", "posicoes": ["MC"], "ovr": 78 },
      { "nome": "Bino", "posicoes": ["MC"], "ovr": 73 },
      { "nome": "Vinho", "posicoes": ["MC"], "ovr": 72 },
      { "nome": "Semes", "posicoes": ["MC"], "ovr": 74 },
      { "nome": "António Folha", "posicoes": ["EXE"], "ovr": 79 },
      { "nome": "Ljubinko Drulović", "posicoes": ["EXE"], "ovr": 82 },
      { "nome": "Jorge Couto", "posicoes": ["EXD"], "ovr": 75 },
      { "nome": "Emil Kostadinov", "posicoes": ["EXD", "PL"], "ovr": 84 },
      { "nome": "Yuran", "posicoes": ["PL"], "ovr": 81 },
      { "nome": "Domingos Paciência", "posicoes": ["PL"], "ovr": 84 },
      { "nome": "Ronald Baroni", "posicoes": ["PL"], "ovr": 71 }
    ]
  },
  {
    "id": "por_1999",
    "nomeEquipa": "Porto 1999",
    "jogadores": [
      { "nome": "Ivica Kralj", "posicoes": ["GR"], "ovr": 76 },
      { "nome": "Rui Correia", "posicoes": ["GR"], "ovr": 75 },
      { "nome": "Vítor Baía", "posicoes": ["GR"], "ovr": 81 },
      { "nome": "Carlos Secretário", "posicoes": ["DD"], "ovr": 78 },
      { "nome": "Jorge Costa", "posicoes": ["DC"], "ovr": 83 },
      { "nome": "Aloísio", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "João Manuel Pinto", "posicoes": ["DC"], "ovr": 76 },
      { "nome": "Carlos Dombray", "posicoes": ["DC"], "ovr": 71 },
      { "nome": "Esquerdinha", "posicoes": ["DE"], "ovr": 77 },
      { "nome": "Fernando Nélson", "posicoes": ["DE"], "ovr": 74 },
      { "nome": "Doriva", "posicoes": ["MC"], "ovr": 80 },
      { "nome": "Zlatko Zahovič", "posicoes": ["MC"], "ovr": 86 },
      { "nome": "Paulinho Santos", "posicoes": ["MC"], "ovr": 78 },
      { "nome": "Peixe", "posicoes": ["MC"], "ovr": 76 },
      { "nome": "Chippo", "posicoes": ["MC"], "ovr": 75 },
      { "nome": "Paulão", "posicoes": ["MC"], "ovr": 74 },
      { "nome": "Fandinho", "posicoes": ["MC"], "ovr": 71 },
      { "nome": "Capucho", "posicoes": ["EXD"], "ovr": 82 },
      { "nome": "Ljubinko Drulović", "posicoes": ["EXE"], "ovr": 83 },
      { "nome": "Alessandro Cambalhota", "posicoes": ["EXE", "PL"], "ovr": 75 },
      { "nome": "Mário Jardel", "posicoes": ["PL"], "ovr": 90 },
      { "nome": "Mielcarski", "posicoes": ["PL"], "ovr": 76 },
      { "nome": "Quinzinho", "posicoes": ["PL"], "ovr": 73 }
    ]
  },
  {
    "id": "por_2003",
    "nomeEquipa": "Porto 2003",
    "jogadores": [
      { "nome": "Vítor Baía", "posicoes": ["GR"], "ovr": 84 },
      { "nome": "Nuno Espírito Santo", "posicoes": ["GR"], "ovr": 73 },
      { "nome": "Paulo Ferreira", "posicoes": ["DD"], "ovr": 82 },
      { "nome": "Secretário", "posicoes": ["DD"], "ovr": 74 },
      { "nome": "Jorge Costa", "posicoes": ["DC"], "ovr": 81 },
      { "nome": "Ricardo Carvalho", "posicoes": ["DC"], "ovr": 85 },
      { "nome": "Pedro Emanuel", "posicoes": ["DC"], "ovr": 79 },
      { "nome": "Ricardo Costa", "posicoes": ["DC"], "ovr": 73 },
      { "nome": "Nuno Valente", "posicoes": ["DE"], "ovr": 80 },
      { "nome": "Mário Silva", "posicoes": ["DE"], "ovr": 75 },
      { "nome": "Costinha", "posicoes": ["MC"], "ovr": 82 },
      { "nome": "Maniche", "posicoes": ["MC"], "ovr": 83 },
      { "nome": "Deco", "posicoes": ["MC"], "ovr": 89 },
      { "nome": "Dmitri Alenichev", "posicoes": ["MC"], "ovr": 79 },
      { "nome": "Tiago", "posicoes": ["MC"], "ovr": 75 },
      { "nome": "Marco Ferreira", "posicoes": ["EXD"], "ovr": 74 },
      { "nome": "Capucho", "posicoes": ["EXD"], "ovr": 77 },
      { "nome": "César Peixoto", "posicoes": ["EXE", "DE"], "ovr": 76 },
      { "nome": "Clayton", "posicoes": ["EXE"], "ovr": 75 },
      { "nome": "Derlei", "posicoes": ["PL", "EXE"], "ovr": 84 },
      { "nome": "Hélder Postiga", "posicoes": ["PL"], "ovr": 79 },
      { "nome": "Edgaras Jankauskas", "posicoes": ["PL"], "ovr": 77 },
      { "nome": "Benni McCarthy", "posicoes": ["PL"], "ovr": 78 }
    ]
  },
  {
    "id": "por_2004",
    "nomeEquipa": "Porto 2004",
    "jogadores": [
      { "nome": "Vítor Baía", "posicoes": ["GR"], "ovr": 86 },
      { "nome": "Nuno", "posicoes": ["GR"], "ovr": 73 },
      { "nome": "Paulo Ferreira", "posicoes": ["DD"], "ovr": 85 },
      { "nome": "Ricardo Carvalho", "posicoes": ["DC"], "ovr": 89 },
      { "nome": "Jorge Costa", "posicoes": ["DC"], "ovr": 82 },
      { "nome": "Pedro Emanuel", "posicoes": ["DC"], "ovr": 79 },
      { "nome": "Ricardo Costa", "posicoes": ["DC"], "ovr": 75 },
      { "nome": "Nuno Valente", "posicoes": ["DE"], "ovr": 82 },
      { "nome": "Mário Silva", "posicoes": ["DE"], "ovr": 74 },
      { "nome": "Costinha", "posicoes": ["MC"], "ovr": 84 },
      { "nome": "Maniche", "posicoes": ["MC"], "ovr": 86 },
      { "nome": "Pedro Mendes", "posicoes": ["MC"], "ovr": 78 },
      { "nome": "Deco", "posicoes": ["MC"], "ovr": 92 },
      { "nome": "Dmitri Alenichev", "posicoes": ["MC"], "ovr": 80 },
      { "nome": "Carlos Alberto", "posicoes": ["MC", "EXD", "EXE"], "ovr": 81 },
      { "nome": "Ricardo Fernandes", "posicoes": ["MC"], "ovr": 72 },
      { "nome": "Marco Ferreira", "posicoes": ["EXD"], "ovr": 73 },
      { "nome": "Maciel", "posicoes": ["EXD", "EXE"], "ovr": 74 },
      { "nome": "César Peixoto", "posicoes": ["EXE"], "ovr": 75 },
      { "nome": "Benni McCarthy", "posicoes": ["PL"], "ovr": 85 },
      { "nome": "Derlei", "posicoes": ["PL", "EXE"], "ovr": 83 },
      { "nome": "Edgaras Jankauskas", "posicoes": ["PL"], "ovr": 76 },
      { "nome": "Bruno Moraes", "posicoes": ["PL"], "ovr": 71 }
    ]
  },
  {
    "id": "por_2009",
    "nomeEquipa": "Porto 2009",
    "jogadores": [
      { "nome": "Helton", "posicoes": ["GR"], "ovr": 82 },
      { "nome": "Nuno", "posicoes": ["GR"], "ovr": 72 },
      { "nome": "Jorge Fucile", "posicoes": ["DD", "DE"], "ovr": 79 },
      { "nome": "Cristian Săpunaru", "posicoes": ["DD"], "ovr": 76 },
      { "nome": "Bruno Alves", "posicoes": ["DC"], "ovr": 83 },
      { "nome": "Rolando", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "Pedro Emanuel", "posicoes": ["DC"], "ovr": 74 },
      { "nome": "Milan Stepanov", "posicoes": ["DC"], "ovr": 73 },
      { "nome": "Aly Cissokho", "posicoes": ["DE"], "ovr": 80 },
      { "nome": "Lucho González", "posicoes": ["MC"], "ovr": 86 },
      { "nome": "Raul Meireles", "posicoes": ["MC"], "ovr": 82 },
      { "nome": "Fernando Reges", "posicoes": ["MC"], "ovr": 81 },
      { "nome": "Fredy Guarín", "posicoes": ["MC"], "ovr": 76 },
      { "nome": "Tomás Costa", "posicoes": ["MC", "DD"], "ovr": 74 },
      { "nome": "Andrés Madrid", "posicoes": ["MC"], "ovr": 71 },
      { "nome": "Lisandro López", "posicoes": ["PL", "EXD", "EXE"], "ovr": 85 },
      { "nome": "Cristian Rodríguez", "posicoes": ["EXE", "EXD"], "ovr": 81 },
      { "nome": "Hulk", "posicoes": ["EXD"], "ovr": 83 },
      { "nome": "Mariano González", "posicoes": ["EXD", "EXE"], "ovr": 75 },
      { "nome": "Tarik Sektioui", "posicoes": ["EXE"], "ovr": 74 },
      { "nome": "Candeias", "posicoes": ["EXD"], "ovr": 70 },
      { "nome": "Ernesto Farías", "posicoes": ["PL"], "ovr": 78 },
      { "nome": "Rabiola", "posicoes": ["PL"], "ovr": 69 }
    ]
  },
  {
    "id": "por_2011",
    "nomeEquipa": "Porto 2011",
    "jogadores": [
      { "nome": "Helton", "posicoes": ["GR"], "ovr": 83 },
      { "nome": "Beto", "posicoes": ["GR"], "ovr": 75 },
      { "nome": "Jorge Fucile", "posicoes": ["DD", "DE"], "ovr": 78 },
      { "nome": "Cristian Săpunaru", "posicoes": ["DD"], "ovr": 77 },
      { "nome": "Rolando", "posicoes": ["DC"], "ovr": 82 },
      { "nome": "Nicolas Otamendi", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "Maicon", "posicoes": ["DC"], "ovr": 78 },
      { "nome": "Sereno", "posicoes": ["DC", "DD", "DE"], "ovr": 73 },
      { "nome": "Álvaro Pereira", "posicoes": ["DE"], "ovr": 82 },
      { "nome": "João Moutinho", "posicoes": ["MC"], "ovr": 86 },
      { "nome": "Fernando Reges", "posicoes": ["MC"], "ovr": 83 },
      { "nome": "Fredy Guarín", "posicoes": ["MC"], "ovr": 82 },
      { "nome": "Belluschi", "posicoes": ["MC"], "ovr": 80 },
      { "nome": "Ruben Micael", "posicoes": ["MC"], "ovr": 76 },
      { "nome": "Souza", "posicoes": ["MC"], "ovr": 73 },
      { "nome": "Hulk", "posicoes": ["EXD"], "ovr": 89 },
      { "nome": "Silvestre Varela", "posicoes": ["EXE", "EXD"], "ovr": 80 },
      { "nome": "James Rodríguez", "posicoes": ["EXE", "MC"], "ovr": 79 },
      { "nome": "Ukra", "posicoes": ["EXD"], "ovr": 72 },
      { "nome": "Christian Atsu", "posicoes": ["EXE"], "ovr": 71 },
      { "nome": "Radamel Falcao", "posicoes": ["PL"], "ovr": 91 },
      { "nome": "Walter", "posicoes": ["PL"], "ovr": 74 },
      { "nome": "Orlando Sá", "posicoes": ["PL"], "ovr": 71 }
    ]
  },
  {
    "id": "por_2018",
    "nomeEquipa": "Porto 2018",
    "jogadores": [
      { "nome": "Iker Casillas", "posicoes": ["GR"], "ovr": 84 },
      { "nome": "José Sá", "posicoes": ["GR"], "ovr": 80 },
      { "nome": "Ricardo Pereira", "posicoes": ["DD", "DE", "EXD"], "ovr": 83 },
      { "nome": "Maxi Pereira", "posicoes": ["DD"], "ovr": 76 },
      { "nome": "Felipe", "posicoes": ["DC"], "ovr": 82 },
      { "nome": "Iván Marcano", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "Diego Reyes", "posicoes": ["DC"], "ovr": 76 },
      { "nome": "Yordan Osorio", "posicoes": ["DC"], "ovr": 72 },
      { "nome": "Alex Telles", "posicoes": ["DE"], "ovr": 83 },
      { "nome": "Danilo Pereira", "posicoes": ["MC"], "ovr": 83 },
      { "nome": "Héctor Herrera", "posicoes": ["MC"], "ovr": 81 },
      { "nome": "Óliver Torres", "posicoes": ["MC"], "ovr": 78 },
      { "nome": "Sérgio Oliveira", "posicoes": ["MC"], "ovr": 77 },
      { "nome": "Otávio", "posicoes": ["MC", "EXD", "EXE"], "ovr": 79 },
      { "nome": "André André", "posicoes": ["MC"], "ovr": 75 },
      { "nome": "Yacine Brahimi", "posicoes": ["EXE"], "ovr": 85 },
      { "nome": "Jesús Corona", "posicoes": ["EXD", "EXE", "DD"], "ovr": 81 },
      { "nome": "Hernâni", "posicoes": ["EXD"], "ovr": 74 },
      { "nome": "Vincent Aboubakar", "posicoes": ["PL"], "ovr": 82 },
      { "nome": "Moussa Marega", "posicoes": ["PL", "EXD"], "ovr": 80 },
      { "nome": "Tiquinho Soares", "posicoes": ["PL"], "ovr": 79 },
      { "nome": "Gonçalo Paciência", "posicoes": ["PL"], "ovr": 74 },
      { "nome": "Waris", "posicoes": ["PL"], "ovr": 73 }
    ]
  },
  {
    "id": "por_2022",
    "nomeEquipa": "Porto 2022",
    "jogadores": [
      { "nome": "Diogo Costa", "posicoes": ["GR"], "ovr": 83 },
      { "nome": "Agustín Marchesín", "posicoes": ["GR"], "ovr": 78 },
      { "nome": "João Mário", "posicoes": ["DD"], "ovr": 77 },
      { "nome": "Rodrigo Conceição", "posicoes": ["DD", "EXD"], "ovr": 69 },
      { "nome": "Pepe", "posicoes": ["DC"], "ovr": 85 },
      { "nome": "Chancel Mbemba", "posicoes": ["DC"], "ovr": 82 },
      { "nome": "Fábio Cardoso", "posicoes": ["DC"], "ovr": 75 },
      { "nome": "Wendell", "posicoes": ["DE"], "ovr": 75 },
      { "nome": "Zaidu Sanusi", "posicoes": ["DE"], "ovr": 74 },
      { "nome": "Vitinha", "posicoes": ["MC"], "ovr": 85 },
      { "nome": "Mateus Uribe", "posicoes": ["MC"], "ovr": 83 },
      { "nome": "Otávio", "posicoes": ["EXD", "EXE", "MC"], "ovr": 82 },
      { "nome": "Pepê", "posicoes": ["EXE", "EXD", "DD", "MC"], "ovr": 79 },
      { "nome": "Fábio Vieira", "posicoes": ["MC", "EXD", "EXE"], "ovr": 79 },
      { "nome": "Stephen Eustáquio", "posicoes": ["MC"], "ovr": 76 },
      { "nome": "Marko Grujić", "posicoes": ["MC"], "ovr": 76 },
      { "nome": "Bruno Costa", "posicoes": ["MC"], "ovr": 72 },
      { "nome": "Luis Díaz", "posicoes": ["EXE"], "ovr": 85 },
      { "nome": "Francisco Conceição", "posicoes": ["EXD"], "ovr": 73 },
      { "nome": "Mehdi Taremi", "posicoes": ["PL"], "ovr": 82 },
      { "nome": "Evanilson", "posicoes": ["PL"], "ovr": 78 },
      { "nome": "Toni Martínez", "posicoes": ["PL"], "ovr": 75 },
      { "nome": "Danny Loader", "posicoes": ["PL", "MC"], "ovr": 68 }
    ]
  },
  {
    "id": "por_2026",
    "nomeEquipa": "Porto 2026",
    "jogadores": [
      { "nome": "Diogo Costa", "posicoes": ["GR"], "ovr": 86 },
      { "nome": "Cláudio Ramos", "posicoes": ["GR"], "ovr": 77 },
      { "nome": "João Costa", "posicoes": ["GR"], "ovr": 75 },
      { "nome": "Martim Fernandes", "posicoes": ["DD", "DE"], "ovr": 78 },
      { "nome": "Alberto Costa", "posicoes": ["DD"], "ovr": 78 },
      { "nome": "Jakub Kiwior", "posicoes": ["DC", "DE"], "ovr": 80 },
      { "nome": "Jan Bednarek", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "Thiago Silva", "posicoes": ["DC"], "ovr": 80 },
      { "nome": "Dominik Prpić", "posicoes": ["DC"], "ovr": 74 },
      { "nome": "Francisco Moura", "posicoes": ["DE"], "ovr": 75 },
      { "nome": "Zaidu Sanusi", "posicoes": ["DE"], "ovr": 75 },
      { "nome": "Alan Varela", "posicoes": ["MC"], "ovr": 81 },
      { "nome": "Pablo Rosario", "posicoes": ["MC", "DE", "DD", "DC"], "ovr": 79 },
      { "nome": "Victor Froholdt", "posicoes": ["MC"], "ovr": 84 },
      { "nome": "Gabri Veiga", "posicoes": ["MC", "EXE"], "ovr": 81 },
      { "nome": "Seko Fofana", "posicoes": ["MC"], "ovr": 78 },
      { "nome": "Oskar Pietuszewski", "posicoes": ["EXE"], "ovr": 79 },
      { "nome": "Rodrigo Mora", "posicoes": ["MC", "EXD", "EXE"], "ovr": 80 },
      { "nome": "Borja Sainz", "posicoes": ["EXE"], "ovr": 77 },
      { "nome": "Samu Omorodion", "posicoes": ["PL"], "ovr": 84 },
      { "nome": "Luuk de Jong", "posicoes": ["PL"], "ovr": 80 },
      { "nome": "Deniz Gül", "posicoes": ["PL"], "ovr": 75 },
      { "nome": "Terem Moffi", "posicoes": ["PL"], "ovr": 73 },
      { "nome": "Pepê", "posicoes": ["EXD", "EXE", "MC", "DD"], "ovr": 81 },
      { "nome": "William Gomes", "posicoes": ["EXD", "EXE"], "ovr": 80 }
    ]
  },
  {
    "id": "por_alltime",
    "nomeEquipa": "Porto All-Time",
    "jogadores": [
      { "nome": "Vítor Baía", "posicoes": ["GR"], "ovr": 89 },
      { "nome": "Helton", "posicoes": ["GR"], "ovr": 85 },
      { "nome": "João Pinto", "posicoes": ["DD"], "ovr": 86 },
      { "nome": "Paulo Ferreira", "posicoes": ["DD"], "ovr": 85 },
      { "nome": "Ricardo Carvalho", "posicoes": ["DC"], "ovr": 91 },
      { "nome": "Pepe", "posicoes": ["DC"], "ovr": 90 },
      { "nome": "Aloísio", "posicoes": ["DC"], "ovr": 85 },
      { "nome": "Jorge Costa", "posicoes": ["DC"], "ovr": 88 },
      { "nome": "Branco", "posicoes": ["DE"], "ovr": 85 },
      { "nome": "Alex Sandro", "posicoes": ["DE"], "ovr": 85 },
      { "nome": "Deco", "posicoes": ["MC"], "ovr": 92 },
      { "nome": "Lucho González", "posicoes": ["MC"], "ovr": 87 },
      { "nome": "Maniche", "posicoes": ["MC"], "ovr": 86 },
      { "nome": "Vitinha", "posicoes": ["MC"], "ovr": 86 },
      { "nome": "Costinha", "posicoes": ["MC"], "ovr": 85 },
      { "nome": "James Rodriguez", "posicoes": ["MC", "EXE"], "ovr": 88 },
      { "nome": "Paulo Futre", "posicoes": ["EXE", "EXD"], "ovr": 91 },
      { "nome": "Rabah Madjer", "posicoes": ["EXD", "PL"], "ovr": 90 },
      { "nome": "Hulk", "posicoes": ["EXD"], "ovr": 90 },
      { "nome": "Luis Díaz", "posicoes": ["EXE"], "ovr": 88 },
      { "nome": "Radamel Falcao", "posicoes": ["PL"], "ovr": 91 },
      { "nome": "Mário Jardel", "posicoes": ["PL"], "ovr": 90 },
      { "nome": "Fernando Gomes", "posicoes": ["PL"], "ovr": 90 }
    ]
  }
];
